# Generated by Django 2.1.2 on 2018-10-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('l', 'Litres'), ('cl', 'Centiliter')], max_length=20)),
            ],
        ),
    ]
