# Generated by Django 2.1.2 on 2018-10-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit_price',
        ),
    ]
