# Generated by Django 2.1.2 on 2018-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_remove_ingredient_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='article_number',
            field=models.IntegerField(default='-1'),
        ),
    ]
