# Generated by Django 2.1.2 on 2018-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_price_count',
            field=models.FloatField(default=0.0),
        ),
    ]
